# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-12 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
