# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-16 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='projects',
            field=models.ManyToManyField(to='projects.Project'),
        ),
    ]
