# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-01-20 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Screen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('orientation', models.CharField(choices=[('Normal (0)', 'Normal (0)'), ('Rotated clockwise (90)', 'Rotated clockwise (90)'), ('Upside down (180)', 'Upside down (180)'), ('Rotated counterclockwise (270)', 'Rotated counterclockwise (270)')], default='Normal (0)', max_length=50)),
                ('description', models.TextField()),
                ('updated', models.DateTimeField(auto_now=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='devices.Device')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.Project')),
            ],
        ),
    ]
